apiVersion: apps/v1
kind: Deployment
metadata:
  name: kodal035 # pod name 
  labels:
    app: container-info # farklı bir deployment ismi verilebilir ama po,rs label ile eşleşmeyeceği için aratmalrda listede çıkmayabilir.
  annotations:
    kubernetes.io/change-cause: deploy/clarus-deploy is set as container-info=clarusway/container-info:3.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container-info # template label ile eşleşmek aynı olmak durumunda aksi halde hangi templateden arttırıp azaltacağını replicaset bilemez.
  template:
    metadata:
      labels:
        app: container-info
    spec:
      containers:
      - name: container
        image: clarusway/container-info:3.0
        ports:
        - containerPort: 80 